version: "3.0"

services:



  keycloak-db:
    image: postgres:latest
    restart: unless-stopped
    container_name: keycloak-db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    volumes:
      - ./data/keycloak_psql:/data/postgres
    networks:
      - spring

  keycloak:
    image: jboss/keycloak:latest
    restart: unless-stopped
    container_name: keycloak
    ports:
      - "8089:8089"
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak
      - DB_SCHEMA=public
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/realms/spring-social.json
    volumes:
      - ./init/keycloak/realms:/opt/jboss/keycloak/realms
    depends_on:
      - keycloak-db
    networks:
      - spring

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongodb
    command: mongod --auth
    networks:
      - spring

  zipkin:
    image: openzipkin/zipkin:latest
    restart: unless-stopped
    ports:
      - "5050:5050"
    container_name: zipkin
    networks:
      - spring

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - spring

  discovery-service:
    image: discovery-service:1.0
    ports:
      - "8780:8780"
    build:
      context: ./DiscoveryService
      dockerfile: ./Dockerfile
    container_name: discovery-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - spring

  api-gateway:
    image: api-gateway:1.0
    ports:
      - "8000:8000"
    build:
      context: ./ApiService
      dockerfile: ./Dockerfile
    container_name: api-gateway
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - spring

  comment-service:
    image: comment-service:1.0
    ports:
      - "8085:8085"
    build:
      context: ./CommentEntity
      dockerfile: ./Dockerfile
    container_name: comment-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - postgresdb
    depends_on:
      - postgresdb
    networks:
      - spring

  post-service:
    image: post-service:1.0
    ports:
      - "8081:8081"
    build:
      context: ./PostEntity
      dockerfile: ./Dockerfile
    container_name: post-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - spring


  friendship-service:
    image: friendship-service:1.0
    ports:
      - "8083:8083"
    build:
      context: ./FriendShipEntity
      dockerfile: ./Dockerfile
    container_name: friendship-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - spring

  user-service:
    image: user-service:1.0
    ports:
      - "8081:8081"
    build:
      context: ./UserEntity
      dockerfile: ./Dockerfile
    container_name: user-service
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - postgresdb
    depends_on:
      - postgresdb
    networks:
      - spring




networks:
  spring:
    driver: bridge